const COUNTRIES = {
    LOAD_DATA: 'LOAD_DATA',
    LOAD_SUCCESS: 'LOAD_SUCCESS',
    LOAD_ERROR: 'LOAD_ERROR',
    OPEN_COUNTRY_DETAILS : 'OPEN_COUNTRY_DETAILS',
    SEARCH_COUNTRIES: 'SEARCH_COUNTRIES',
    FILTER_BY_REGION: 'FILTER_BY_REGION',
    ON_CHANGE: 'ON_CHANGE',
    SUBMIT: 'SUBMIT'
}

export {COUNTRIES}