const COUNTRIES = {
    LOAD_DATA: 'LOAD_DATA',
    LOAD_SUCCESS: 'LOAD_SUCCESS',
    LOAD_ERROR: 'LOAD_ERROR',
    OPEN_COUNTRY_DETAILS : 'OPEN_COUNTRY_DETAILS',
    SEARCH_COUNTRIES: 'SEARCH_COUNTRIES',
    FILTER_BY_REGION: 'FILTER_BY_REGION',
    ON_CHANGE: 'ON_CHANGE',
    SUBMIT: 'SUBMIT'
}

const COUNTRIES_DETAILS = {
    GET_DATA: 'GET_DATA',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_ERROR: 'GET_ERROR',
}

const SEARCH_COUNTRIES = {
    SEARCH_DATA: 'SEARCH_DATA',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_ERROR: 'SEARCH_ERROR',
}

const SEARCH_INPUT_VALUE = {
    CHANGE : 'CHANGE',
    SUBMIT : 'SUBMIT'
}

export {COUNTRIES, COUNTRIES_DETAILS, SEARCH_COUNTRIES, SEARCH_INPUT_VALUE}